apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbit-state
  namespace: kubesat-dev
  labels:
    app.kubernetes.io/part-of: kubesat
    app.kubernetes.io/component: dispatcher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
