apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesat-dispatcher
  namespace: kubesat-dev
  labels:
    app.kubernetes.io/part-of: kubesat
    app.kubernetes.io/component: dispatcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubesat-job-manager
  namespace: kubesat-dev
  labels:
    app.kubernetes.io/part-of: kubesat
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubesat-dispatcher-job-manager
  namespace: kubesat-dev
  labels:
    app.kubernetes.io/part-of: kubesat
subjects:
  - kind: ServiceAccount
    name: kubesat-dispatcher
    namespace: kubesat-dev
roleRef:
  kind: Role
  name: kubesat-job-manager
  apiGroup: rbac.authorization.k8s.io
